spring.application.name=gateway
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true

# Gateway HTTP timeouts (keep reasonable)
spring.cloud.gateway.httpclient.connect-timeout=5000
spring.cloud.gateway.httpclient.response-timeout=10s

# ---------- AUTH ROUTE ----------
spring.cloud.gateway.routes[0].id=auth
spring.cloud.gateway.routes[0].uri=lb://auth
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# ---------- SVC-JAVA ROUTE WITH CIRCUIT BREAKER ----------
spring.cloud.gateway.routes[1].id=svc-java
spring.cloud.gateway.routes[1].uri=lb://svc-java
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.name=javaService
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/fallback/java
spring.cloud.gateway.routes[1].filters[0].args.statusCodes=500,502,503,504

spring.cloud.gateway.routes[1].filters[1].name=RequestRateLimiter
spring.cloud.gateway.routes[1].filters[1].args.redis-rate-limiter.replenishRate=100
spring.cloud.gateway.routes[1].filters[1].args.redis-rate-limiter.burstCapacity=100
spring.cloud.gateway.routes[1].filters[1].args.key-resolver=#{@userKeyResolver}

spring.cloud.gateway.routes[1].filters[2].name=AddRequestHeader
spring.cloud.gateway.routes[1].filters[2].args.name=X-Gateway-Token
spring.cloud.gateway.routes[1].filters[2].args.value=GATEWAY_SECRET_123



resilience4j.timelimiter.instances.javaService.timeoutDuration=10s
resilience4j.timelimiter.instances.javaService.cancelRunningFuture=true


resilience4j.circuitbreaker.instances.javaService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.javaService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.javaService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.javaService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.javaService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.javaService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.javaService.automaticTransitionFromOpenToHalfOpenEnabled=true


